# Generated by Django 4.2.1 on 2023-07-28 14:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210712_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
